# Generated by Django 5.2 on 2025-07-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('assignee', models.CharField(max_length=100)),
            ],
        ),
    ]
