# Generated by Django 5.2 on 2025-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Inspection', 'Inspection'), ('Operational', 'Operational')], max_length=50)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
